### ISSUE TITLE
Rethinking the Queue class to get full GPU utilization

### ISSUE THREAD

**Issue by dmus** [fepegar/torchio#393]
This is a really nice framework, however a serious issue for me is (the lack of) GPU utilization. This is an issue even with only a simple ZNormalization and a left right flip of the data as augmentation. This results in the following GPU utilization:
![Screenshot from 2020-12-22 12-12-31](https://user-images.githubusercontent.com/464378/102882714-188e0d80-444f-11eb-995c-4168ca7b3b24.png)

This is a training with 5 subjects and sampling 40 patches per volume and batch size 8. After every 25 iterations (which means 200 patches) there is a gap and the GPU utilization is 0.

What I did is building a custom Queue class in which I tried to get full GPU utilization. The result is as follows:
![Screenshot from 2020-12-22 12-05-10](https://user-images.githubusercontent.com/464378/102883050-a79b2580-444f-11eb-80de-3fbf556b78b3.png)
As you can see this has a GPU utilization of ~100%.

I tried to use the existing PyTorch data functionalities as much as possible. The BufferedShuffleDataset is something that is not yet in the release, but seems to be in the next release. The idea behind it is the same as for the shuffle() in Tensorflow data.

Here is the code that I made:

```
import random
from itertools import islice
from typing import Iterator, List

import torch
torch.multiprocessing.set_sharing_strategy('file_system')
from torch.utils.data import DataLoader, IterableDataset
from torch.utils.data.dataset import T_co
from torchio.data import PatchSampler



# https://github.com/pytorch/pytorch/commit/96540e918c4ca3f0a03866b9d281c34c65bd76a4#diff-425b66e1ff01d191679c386258a7156dfb5aacd64a8e0947b24fbdebcbee8529
class BufferedShuffleDataset(IterableDataset[T_co]):
    r"""Dataset shuffled from the original dataset.
    This class is useful to shuffle an existing instance of an IterableDataset.
    The buffer with `buffer_size` is filled with the items from the dataset first. Then,
    each item will be yielded from the buffer by reservoir sampling via iterator.
    `buffer_size` is required to be larger than 0. For `buffer_size == 1`, the
    dataset is not shuffled. In order to fully shuffle the whole dataset, `buffer_size`
    is required to be greater than or equal to the size of dataset.
    When it is used with :class:`~torch.utils.data.DataLoader`, each item in the
    dataset will be yielded from the :class:`~torch.utils.data.DataLoader` iterator.
    And, the method to set up a random seed is different based on :attr:`num_workers`.
    For single-process mode (:attr:`num_workers == 0`), the random seed is required to
    be set before the :class:`~torch.utils.data.DataLoader` in the main process.
        >>> ds = BufferedShuffleDataset(dataset)
        >>> random.seed(...)
        >>> print(list(torch.utils.data.DataLoader(ds, num_workers=0)))
    For multi-process mode (:attr:`num_workers > 0`), the random seed is set by a callable
    function in each worker.
        >>> ds = BufferedShuffleDataset(dataset)
        >>> def init_fn(worker_id):
        ...     random.seed(...)
        >>> print(list(torch.utils.data.DataLoader(ds, ..., num_workers=n, worker_init_fn=init_fn)))
    Arguments:
        dataset (IterableDataset): The original IterableDataset.
        buffer_size (int): The buffer size for shuffling.
    """
    dataset: IterableDataset[T_co]
    buffer_size: int

    def __init__(self, dataset: IterableDataset[T_co], buffer_size: int) -> None:
        super(BufferedShuffleDataset, self).__init__()
        assert buffer_size > 0, "buffer_size should be larger than 0"
        self.dataset = dataset
        self.buffer_size = buffer_size

    def __iter__(self) -> Iterator[T_co]:
        buf: List[T_co] = []
        for x in self.dataset:
            if len(buf) == self.buffer_size:
                idx = random.randint(0, self.buffer_size - 1)
                yield buf[idx]
                buf[idx] = x
            else:
                buf.append(x)
        random.shuffle(buf)
        while buf:
            yield buf.pop()


class PatchesDataset(IterableDataset):
    def __init__(self, subjects_dataset, sampler, samples_per_volume):
        self.subjects_dataset = subjects_dataset
        self.sampler = sampler
        self.samples_per_volume = samples_per_volume

    def __iter__(self):
        while True:
            idx = random.randint(0, len(self.subjects_dataset) - 1)
            sample = self.subjects_dataset[idx]
            iterable = self.sampler(sample)
            patches = list(islice(iterable, self.samples_per_volume))

            yield patches


class Queue(IterableDataset):
    def __init__(
            self,
            subjects_dataset: PatchesDataset,
            max_length: int,
            samples_per_volume: int,
            sampler: PatchSampler,
            num_workers: int = 0,
            shuffle_subjects: bool = True,
            shuffle_patches: bool = True,
            verbose: bool = False,
    ):
        self.dataset = PatchesDataset(subjects_dataset, sampler, samples_per_volume)
        self.max_length = max_length

        self.loader = DataLoader(self.dataset,
                                 batch_size=None,
                                 num_workers=num_workers,
                                 persistent_workers=True)

        self.buffer = []

    def __iter__(self):
        # Basically this is an unbatch operation
        for patches_list in self.loader:
            for patch in patches_list:
                yield patch

```
As you can see I had to do:
```
import torch
torch.multiprocessing.set_sharing_strategy('file_system')
```
because otherwise I got this error: RuntimeError: received 0 items of ancdata

This may be something in the system that I use, but it seems to be a more common thing, see:
https://github.com/pytorch/pytorch/issues/973

With using this custom implementation I could use:
```
        # patches_queue = tio.Queue(
        #     self.dataset,
        #     max_length=self.queue_length,
        #     samples_per_volume=self.samples_per_volume,
        #     sampler=sampler,
        #     num_workers=self.num_workers,
        #     verbose=False
        # )

        # use the custom queue instead of the default one
        queue = Queue(self.dataset,
                      max_length=self.queue_length,
                      samples_per_volume=self.samples_per_volume,
                      sampler=sampler,
                      num_workers=self.num_workers,
                      verbose=False)
        patches_queue = BufferedShuffleDataset(queue, self.queue_length)

        patches_loader = DataLoader(patches_queue, batch_size=self.batch_size)
```

What do you think of this? Could this replace or exist next to the existing tio.Queue?

**Comment by fepegar** [comment]
Hi, @dmus. I haven't fully understood how this works, but it certainly looks promising. So would the samplers need to be reimplemented as well? How random is this? The way the current queue works is
1. Shuffle subjects
2. Extract N patches from subjects until the buffer is full
3. Shuffle the buffer
4. Pop patches from the buffer
5. If the buffer is empty, go to 2.

This ensures that batches of patches come from different subjects. Is this also ensured? And would all the subjects be sampled as well? If this works well, we could synchronize it with the release of PyTorch 1.8.

---

What tool do you use to visualize GPU utilization?

**Comment by dmus** [comment]
The tool for GPU utilization is Grafana. This uses the existing samplers, no need for reimplementation. 

How this custom queue works is:
1. Select a random subject (in each worker)
2. Extract N patches from the subject (in this implementation also in the worker)
3. In the main process: fill the buffer with patches until the buffer is full
4. Pick a random patch from the buffer and replace this with a new patch

> This ensures that batches of patches come from different subjects. Is this also ensured?
Each worker picks a random subject, so in that way patches come from different subjects. The buffer size should be large enough to have samples from different subjects

I also tried with a map-style Dataset instead of an iterable dataset for the PatchesDataset. Then each subjects is sampled once, but I was getting (small) gaps in GPU utilization with this approach

> And would all the subjects be sampled as well?
In theory when you sample long enough you should have about the same number of samples from each subject

**Comment by fepegar** [comment]
Nice. Using a map-style dataset would ensure that patches are extracted from each subject once, and would let us define an epoch, right? I'm not sure why that approach would be less optimized than the iterable dataset.

**Comment by dmus** [comment]
> Nice. Using a map-style dataset would ensure that patches are extracted from each subject once, and would let us define an epoch, right?

Yes that is right

 

> I'm not sure why that approach would be less optimized than the iterable dataset.

I also don't know. Maybe because after each epoch things have to be initialized again, but not sure

**Comment by fepegar** [comment]
The buffered shuffle dataset seems to be available in the nightly version:

```
 Py 3.8.5 (test)  ~  pip install numpy                                                                                                      ✔  26% (2:18)  24.63s  13:49:21
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting numpy
  Using cached numpy-1.19.4-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
Installing collected packages: numpy
Successfully installed numpy-1.19.4
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch-1.8.0.dev20201222-cp38-none-macosx_10_9_x86_64.whl (115.5 MB)
     |████████████████████████████████| 115.5 MB 15 kB/s
Requirement already satisfied: numpy in /usr/local/Caskroom/miniconda/base/envs/test/lib/python3.8/site-packages (from torch) (1.19.4)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/nightly/torchvision-0.9.0.dev20201222-cp38-cp38-macosx_10_9_x86_64.whl (13.1 MB)
     |████████████████████████████████| 13.1 MB 7.8 MB/s
Collecting pillow>=4.1.1
  Using cached Pillow-8.0.1-cp38-cp38-macosx_10_10_x86_64.whl (2.2 MB)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Installing collected packages: typing-extensions, torch, pillow, torchvision
Successfully installed pillow-8.0.1 torch-1.8.0.dev20201222 torchvision-0.9.0.dev20201222 typing-extensions-3.7.4.3
 Py 3.8.5 (test)  ~  ipython                                                                                                                 ✔  26% (2:20)  01:09  13:50:46
import Python 3.8.5 (default, Sep  4 2020, 02:22:02)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: torch.__version__
Out[2]: '1.8.0.dev20201222'

In [3]: from torch.utils.data.dataset import BufferedShuffleDataset
```

I won't have much time in the next two months. Would you like to submit a PR with your proposal? I thought that `BufferedShuffleQueue` might be appropriate, but I'm not sure because the current queue is also buffered and typically shuffled.

**Comment by dmus** [comment]
I will test and work it out a bit more and then submit a PR

**Comment by dmus** [comment]
To come back to this issue. The implementation now looks like this

```
class BatchedPatchesDataset(IterableDataset):

    def __init__(self, subjects_datasets, weights, sampler, samples_per_volume):
        self.subjects_datasets = subjects_datasets
        self.weights = weights
        self.sampler = sampler
        self.samples_per_volume = samples_per_volume

    def __iter__(self):
        while True:
            sampled_dataset = random.choices(population=self.subjects_datasets, weights=self.weights)[0]
            idx = random.randint(0, len(sampled_dataset) - 1)
            sample = sampled_dataset[idx]
            iterable = self.sampler(sample)
            patches = list(islice(iterable, self.samples_per_volume))

            yield patches


class UnbatchDataset(IterableDataset):

    def __init__(
            self,
            dataset: Dataset,
            num_workers: int = 0,
    ):
        self.loader = DataLoader(dataset,
                                                 batch_size=None,
                                                 num_workers=num_workers)

    def __iter__(self):
        for batch in self.loader:
            yield from batch
```

To use it:

```
    # This yields a dataset with non random batches of batch_size 'samples_per_volume' 
    to_patches = BatchedPatchesDataset(subjects_datasets=[dataset],
                                                                  weights=[1], # Only relevant when sampling from multiple subject datasets
                                                                  sampler=sampler,
                                                                  samples_per_volume=samples_per_volume)
    # Unbatch the batches
    patches_unbatched = UnbatchDataset(to_patches, num_workers)

    # Shuffle to get the patches in a random order
    queue = BufferedShuffleDataset(patches_unbatched, max_queue_length)

    patches_loader = DataLoader(queue, batch_size=batch_size)

    for i, patches_batch in enumerate(patches_loader):
        inputs = patches_batch['ct'][tio.DATA].numpy()
        targets = patches_batch['labels'][tio.DATA].numpy()

```

For my use case this gives good gpu utilization and a big speed up. But it would be good to also know about other use cases. Shall I submit a pull request?

**Comment by dmus** [comment]
1. Yes, this can be changed to accept both one dataset and a list of datasets with corresponding weights. 
2. This would be difficult I think (and for more complex use cases with datasets from multiple centers probably not desired, how to define a traditional epoch there). At least this would require using map-style datasets instead of iterable datasets I think. 
3. a. correct
    b. it iterates over the list from a. and returns the individual items (a patch sampled from the original subject, not a list anymore). Unbatch does what is described here too: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#unbatch

**Comment by rousseau** [comment]
As found by dmus, we have also encoutered this "issue" (i.e. not full use of GPU). 

Is there a way to use TorchIO with queues optimized for GPU ?

**Comment by romainVala** [comment]
no solution has been incorporated into current torchio, 
but did you test dmus 's solution 
it worth to try, although not easy to choose the best parameters

**Comment by rousseau** [comment]
I've tried to use dmus's solution. GPU is fully used but the training does not end !

To avoid the gaps mentioned by dmus, within current TorchIO, what do you recommend ? 
- Largest queue as possible ?
- Many workers as possible ?
- ... ?

**Comment by fepegar** [comment]
Hi, @rousseau. I do recommend a long queue, multiple workers (sometimes fewer than the maximum is faster, for example I typically use 12/40 in a DGX after benchmarking), many samples per volume, and fast transforms (avoid RandomElasticDeformation, RandomMotion, maybe RandomBiasField). If you have a lot of storage, you can store your images uncompressed (e.g. `.nii` instead of `.nii.gz`) or, even better, preload the preprocessed images on the RAM for faster access. Just watch out for the RAM usage. You can use [`get_max_memory_pretty`](https://torchio.readthedocs.io/data/patch_training.html#torchio.data.Queue.get_max_memory_pretty). But remember some operations (e.g. the transforms) will also need RAM, so don't use all of it for the queue.

**Comment by dmus** [comment]
Implementation is updated in the meantime to use the Torch DataPipes (see https://github.com/pytorch/data):

`from itertools import islice

import torchio as tio
from torch.utils.data import DataLoader
from torch.utils.data import IterDataPipe
from torch.utils.data.datapipes.iter import Shuffler, UnBatcher

batch_size = 32
num_workers = 8
samples_per_volume = 20
sampler = tio.UniformSampler(patch_size=64)


class PatchesSampler(IterDataPipe):

    def __init__(self, datapipe, sampler, samples_per_volume):
        self.datapipe = datapipe
        self.sampler = sampler
        self.samples_per_volume = samples_per_volume

    def __iter__(self):
        for subject in self.datapipe:
            iterable = self.sampler(subject)
            yield list(islice(iterable, self.samples_per_volume))

datapipe = PatchesSampler(my_dataset, sampler, samples_per_volume)
datapipe = DataLoader(datapipe, batch_size=None, num_workers=num_workers)

datapipe = UnBatcher(datapipe)
datapipe = Shuffler(datapipe, buffer_size=batch_size * samples_per_volume)
dataloader = DataLoader(datapipe, batch_size=batch_size)

while True:
    for batch in dataloader:
        ...
`

**Comment by Paddy-Xu** [comment]
> Implementation is updated in the meantime to use the Torch DataPipes (see [pytorch/data](https://github.com/pytorch/data)):
> 
> ```python
> from itertools import islice
> 
> import torchio as tio
> from torch.utils.data import DataLoader
> from torch.utils.data import IterDataPipe
> from torch.utils.data.datapipes.iter import Shuffler, UnBatcher
> 
> batch_size = 32
> num_workers = 8
> samples_per_volume = 20
> sampler = tio.UniformSampler(patch_size=64)
> 
> 
> class PatchesSampler(IterDataPipe):
> 
>     def __init__(self, datapipe, sampler, samples_per_volume):
>         self.datapipe = datapipe
>         self.sampler = sampler
>         self.samples_per_volume = samples_per_volume
> 
>     def __iter__(self):
>         for subject in self.datapipe:
>             iterable = self.sampler(subject)
>             yield list(islice(iterable, self.samples_per_volume))  # in my experience this turned out to be faster than using yield from islice(iterable, self.samples_per_volume)) and removing the UnBatcher
> 
> datapipe = PatchesSampler(my_dataset, sampler, samples_per_volume)
> datapipe = DataLoader(datapipe, batch_size=None, num_workers=num_workers)
> 
> datapipe = UnBatcher(datapipe)
> datapipe = Shuffler(datapipe, buffer_size=batch_size * samples_per_volume)
> dataloader = DataLoader(datapipe, batch_size=batch_size)
> 
> while True:
>     for batch in dataloader:
>         ...
> ```

Hi, Thank you very much! This does increase the utilization. However, It seems that I have to always set num_workers=0 in this case, and could you please explain a bit why the first batchsize in DataLoader is None and buffer size is batch_size * samples_per_volume? Thanks a lot!

**Comment by tiago972** [comment]
First of all, thank you for this wrapper package and to @dmus to assess this issue as this has been a major limit in my case.

However, using the last proposition, if I use num_workers > 0 in `datapipe = DataLoader(datapipe, batch_size=None, num_workers=num_workers)` this raises :
RuntimeError: unable to mmap 192 bytes from file </torch_2753772_2515325872_1186>: Cannot allocate memory (12)

However, this is not raise with num_workers = 0 or if num_workers > 0 and pin_memory = True but the latter leads to memory leak.

This is not a memory issue as I have access to 255 CPUs and a NVIDIA-SMI 510.47.03 with 40Gb of memory.

Have you encounter such issue?

Chears, 
Tiago

**Comment by Jesse-Phitidis** [comment]
I was also experiencing some frustration with the low GPU utilisation of the Queue class, so here is my pitch:

**Pitch**

Replace the `Queue` class with the `SubjectsPatchDataset` class below (inherits from `SubjectsDataset`, but extracts `patches_per_subject` patches in each call to `__getitem__`, and returns a list of these patches). Then use a custom data loader instead of the Pytorch one, to work with this type of dataset; `BufferedShuffledLoader`, below.

This approach maintains the important aspects of the existing `Queue` class + Pytorch `DataLoader` approach, i.e. it loads exactly `patches_per_subject` patches for every subject in one epoch and the generator runs out after exactly this time, so we define an epoch. Once the queue size patches have been enqueued, the queue is shuffled. The benefit of this approach is that we can prefetch patches so we don't need to wait for the queue to fill from scratch each time it is emptied. For me, training a 3D U-Net using a dataset of 147 subjects, with 8 samples per subject and max queue size of 1176 (147 * 8), with 8 workers, on a workstation with an AMD Ryzen Threadripper PRO 5955WX 16-Cores CPU and and RTX 4090 GPU, I improved the training time by about 40% compared to the same settings using `Queue` + `DataLoader`. I also reduced the average memory consumption (although I haven't figured out why!). You can see the plots below.

| ![Image](https://github.com/user-attachments/assets/64d841ab-11ac-4a86-9f6d-a962fcc66405) | ![Image](https://github.com/user-attachments/assets/80f0ca5a-6b63-41b9-bce6-ca8da82bfc85) | ![Image](https://github.com/user-attachments/assets/b59b1a5f-6525-49eb-bceb-810c12e6d871) |
|---|---|---|


```python
import torchio as tio
from torchio import Subject
from typing import Any, List, Optional, Iterator, Callable
import multiprocessing as mp
from multiprocessing.synchronize import Event
import threading
import random
import time
import queue
from cvdseg.data_modules.dataset import SubjectsPatchDataset

class SubjectsPatchDataset(tio.SubjectsDataset):

    def __init__(self, sampler, patches_per_subject, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._sampler = sampler
        self._patches_per_subject = patches_per_subject

    def __getitem__(self, *args, **kwargs):
        subject = super().__getitem__(*args, **kwargs)
        patches = []
        iterator = self._sampler(subject)
        for _ in range(self._patches_per_subject):
            patches.append(next(iterator))
        return patches

    def __len__(self):
        return len(self._subjects) * self._patches_per_subject


class BufferedShuffledLoader:
    """A custom data loader for efficiently loading and batching patches from a SubjectsPatchDataset.
    
    This loader supports multi-process data loading with configurable queue sizes and
    batch processing capabilities.
    
    Args:
        dataset: The dataset to load patches from
        batch_size: Number of patches per batch
        shuffle: Whether to shuffle the data between epochs
        num_workers: Number of worker processes for data loading
        queue_max_length: Maximum size of the loading queue
        collate_fn: Optional custom collation function
        spread_queue: Whether to spread patches from same subject across queue
    """
    
    def __init__(
        self,
        dataset: SubjectsPatchDataset,
        batch_size: int,
        shuffle: bool,
        num_workers: int,
        queue_max_length: int,
        collate_fn: Optional[Callable] = None,
        spread_queue: bool = False
    ):
        if batch_size > queue_max_length:
            raise ValueError("batch_size must be <= queue_max_length")
            
        self.dataset = dataset
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.num_workers = num_workers
        self.queue_max_length = queue_max_length
        self.collate_fn = collate_fn if collate_fn is not None else self._collate
        self.queue_shuffle_fn = random.shuffle if not spread_queue else self._spread_queue_fn
        
        # Initialize queues and process management
        self._initialize_queues()
        
        self.patch_list: List[Any] = []
        self.patch_list_end: List[Any] = []
        self.patch_list_end_max_size = len(self.dataset) % self.queue_max_length
        
        self.current_sample = None # For direct loading (num_workers=0)
        self.current_sample_idx = 0 # For direct loading (num_workers=0)
        self.num_queue_entries_popped = len(self.dataset)  # Start at epoch boundary
        
        if self.num_workers > 0:
            self._start_workers()

    def _initialize_queues(self) -> None:
        """Initialize the task and result queues based on worker configuration."""
        if self.num_workers > 0:
            self.manager = mp.Manager()
            self.task_queue = self.manager.Queue(maxsize=len(self.dataset) // self.dataset._patches_per_subject)
            self.result_queue = self.manager.Queue(maxsize=self.queue_max_length)
            self.stop_event = self.manager.Event()
        else:
            self.manager = None
            self.task_queue = queue.Queue(maxsize=len(self.dataset) // self.dataset._patches_per_subject)
            self.result_queue = queue.Queue(maxsize=self.queue_max_length)
            self.stop_event = None

    def _start_workers(self) -> None:
        """Start worker processes for parallel data loading."""
        self.processes = []
        for _ in range(self.num_workers):
            p = mp.Process(
                target=self._worker,
                args=(self.task_queue, self.result_queue, self.dataset, self.stop_event)
            )
            p.start()
            self.processes.append(p)

    def _worker(
        self,
        task_queue: mp.Queue,
        result_queue: mp.Queue,
        dataset: SubjectsPatchDataset,
        stop_event: Event
    ) -> None:
        """Worker process function for loading data.
        
        Args:
            task_queue: Queue containing indices to process
            result_queue: Queue to store processed results
            dataset: Dataset to load from
            stop_event: Event to signal worker termination
        """
        while not stop_event.is_set():
            try:
                idx = task_queue.get(timeout=1)
                samples = dataset[idx]
                samples_added = 0
                while samples_added < dataset._patches_per_subject:
                    if (self.num_stored_patches + 1) <= self.queue_max_length:
                        result_queue.put(samples[samples_added])
                        samples_added += 1
                    if stop_event.is_set():
                        break
            except queue.Empty:
                continue

    def _load_patches_directly(self) -> None:
        """Load patches directly when not using worker processes."""
        try:
            if self.current_sample is None:
                idx = self.task_queue.get(timeout=1)
                self.current_sample = self.dataset[idx]
                self.current_sample_idx = 0
            if (self.num_stored_patches + 1) <= self.queue_max_length:
                self.result_queue.put(self.current_sample[self.current_sample_idx])
                if len(self.current_sample) == self.current_sample_idx + 1:
                    self.current_sample = None
                else:
                    self.current_sample_idx += 1
        except queue.Empty:
            pass

    def _enqueue_samples(self, indices: List[int]) -> None:
        """Add sample indices to the task queue.
        
        Args:
            indices: List of dataset indices to enqueue
        """
        for idx in indices:
            self.task_queue.put(idx)

    def _prefetch_next_epoch(self) -> None:
        """Background thread function to prepare next epoch's data."""
        while not (self.stop_event.is_set() if self.num_workers > 0 else False):
            time.sleep(0.1)
            if self.num_queue_entries_popped < len(self.dataset):
                continue
            indices = list(range(len(self.dataset) // self.dataset._patches_per_subject))
            self.num_queue_entries_popped = 0
            if self.shuffle:
                random.shuffle(indices)
            self._enqueue_samples(indices)

    def _pop_queue_to_list(self, queue_obj: queue.Queue, target_list: List, n: Optional[int] = None) -> None:
        """Move items from a queue to a list.
        
        Args:
            queue_obj: Source queue
            target_list: Target list
            n: Optional limit on number of items to move
        """
        if n is None:
            while not queue_obj.empty():
                target_list.append(queue_obj.get())
                self.num_queue_entries_popped += 1
        else:
            for _ in range(n):
                target_list.append(queue_obj.get())
                self.num_queue_entries_popped += 1

    def _pop_list_to_list(self, source_list: List, target_list: List) -> None:
        """Move all items from one list to another.
        
        Args:
            source_list: Source list
            target_list: Target list
        """
        while source_list:
            target_list.append(source_list.pop())

    def _extract_batch(self) -> dict:
        """Extract a batch of patches from the patch list.
        
        Returns:
            Collated batch dictionary
        """
        batch_list = []
        for _ in range(min(len(self.patch_list), self.batch_size)):
            batch_list.append(self.patch_list.pop())
        return self.collate_fn(batch_list)

    def __iter__(self) -> Iterator[dict]:
        """Create an iterator over batches in the dataset."""
        prefetch_thread = threading.Thread(target=self._prefetch_next_epoch, daemon=True)
        prefetch_thread.start()

        for _ in range(len(self)):
            while len(self.patch_list) == 0:
                if self.num_workers == 0:
                    self._load_patches_directly()
                
                remaining_patches = len(self.dataset) - self.num_queue_entries_popped
                if self.task_queue.empty() and remaining_patches == self.patch_list_end_max_size:
                    while self.num_queue_entries_popped < len(self.dataset):
                        if self.num_workers == 0:
                            self._load_patches_directly()
                        self._pop_queue_to_list(self.result_queue, self.patch_list_end)
                
                if self.patch_list_end:
                    self._pop_list_to_list(self.patch_list_end, self.patch_list)
                    self.queue_shuffle_fn(self.patch_list)
                elif self.result_queue.full():
                    self._pop_queue_to_list(self.result_queue, self.patch_list, self.queue_max_length)
                    self.queue_shuffle_fn(self.patch_list)
            
            yield self._extract_batch()

    def stop_workers(self) -> None:
        """Stop all worker processes."""
        if self.num_workers == 0:
            return
        self.stop_event.set()
        for p in self.processes:
            p.join()

    def __len__(self) -> int:
        """Calculate total number of batches per epoch."""
        n_full_queues = len(self.dataset) // self.queue_max_length
        n_iters_for_full_queue = (self.queue_max_length // self.batch_size)
        n_iters_for_full_queue += (1 if self.queue_max_length % self.batch_size > 0 else 0)
        n_iters_for_part_queue = (self.patch_list_end_max_size // self.batch_size)
        n_iters_for_part_queue += (1 if self.patch_list_end_max_size % self.batch_size > 0 else 0)
        return n_full_queues * n_iters_for_full_queue + n_iters_for_part_queue

    def __del__(self) -> None:
        """Clean up resources when the loader is deleted."""
        self.stop_workers()

    @property
    def num_stored_patches(self) -> int:
        """Get approximate number of patches currently stored.
        
        Returns:
            Total number of patches across all storage locations (not including those held by workers)
        """
        return len(self.patch_list) + len(self.patch_list_end) + self.result_queue.qsize()

    @staticmethod
    def _collate(subjects: List[Subject]) -> dict[str, Any]:
        """Collate a list of subjects into a batch dictionary. From torchio.data.SubjectsLoader.
        
        Args:
            subjects: List of subjects to collate
            
        Returns:
            Dictionary containing batched data
        """
        first_subject = subjects[0]
        batch_dict = {}
        for key in first_subject.keys():
            collated_value = _stack([subject[key] for subject in subjects])
            batch_dict[key] = collated_value
        return batch_dict

    def _spread_queue_fn(self, patches: List[Any]) -> None:
        """Spread patches from the same subject across the queue.
        
        Args:
            patches: List of patches to spread
        """
        n = self.dataset._patches_per_subject
        temp = patches[:]
        index = 0
        for i in range(n):
            for item in temp[i::n]:
                patches[index] = item
                index += 1


def _stack(x):
    """Determine the type of the input and stack it accordingly. From torchio.data.loader.

    Args:
        x: List of elements to stack.
    Returns:
        Stacked elements, as either a torch.Tensor, np.ndarray, dict or list.
    """
    first_element = x[0]
    if isinstance(first_element, torch.Tensor):
        return torch.stack(x, dim=0)
    elif isinstance(first_element, np.ndarray):
        return np.stack(x, axis=0)
    elif isinstance(first_element, dict):
        # Assume that all elements have the same keys
        collated_dict = {}
        for key in first_element.keys():
            collated_dict[key] = _stack([element[key] for element in x])
        return collated_dict
    else:
        return x
```

If anyone want to use it, here is a test to convince yourself that it works, or to let me know if you break it!

```python
import numpy as np
from collections import defaultdict, Counter
from itertools import product

def test(
    loader_cls,
    get_item_delay, 
    forward_pass_delay,
    num_subjects, 
    patch_size, 
    patches_per_subject, 
    batch_size, 
    num_workers, 
    queue_max_length, 
    num_epochs):
    
    class SubjectsPatchDataset(tio.SubjectsDataset):

        def __init__(self, sampler, patches_per_subject, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._sampler = sampler
            self._patches_per_subject = patches_per_subject

        def __getitem__(self, *args, **kwargs):
            subject = super().__getitem__(*args, **kwargs)
            patches = []
            iterator = self._sampler(subject)
            for _ in range(self._patches_per_subject):
                patches.append(next(iterator))
            time.sleep(get_item_delay)
            return patches

        def __len__(self):
            return len(self._subjects) * self._patches_per_subject
    
    
    subjects = [tio.datasets.Colin27() for _ in range(num_subjects)]
    for i, s in enumerate(subjects):
        s["id"] = i
    
    sampler = tio.data.UniformSampler(patch_size=patch_size)

    dataset = SubjectsPatchDataset(subjects=subjects, sampler=sampler, patches_per_subject=patches_per_subject)
    
    loader = loader_cls(
        dataset=dataset, 
        batch_size=batch_size, 
        shuffle=True, 
        num_workers=num_workers, 
        queue_max_length=queue_max_length, 
        spread_queue=False
        )
    
    for epoch in range(num_epochs):
        d = defaultdict(lambda : 0)
        for i, batch in enumerate(loader):
            for j in batch["id"]:
                d[j] += 1
            time.sleep(forward_pass_delay)

        counter = Counter(d)
        assert len(counter) == num_subjects
        assert np.all(list(counter.values()) == [patches_per_subject] * num_subjects)
```

**Comment by Jesse-Phitidis** [comment]
> Hello thanks for sharing, it looks interesting [@Jesse-Phitidis](https://github.com/Jesse-Phitidis), One draw back of your proposition, is that the queue is no more shulffled ?
> 
> you will end up with batch of patches from the same subject .. ?
> 
> or do I miss something ?

Thanks for checking this out. The patches are indeed shuffled once they have been moved from the multiprocess queue to the patch_list (last line before yield) and from the patch_list_end list to the patch_list (a couple lines above).
